version: '3.7'
services:
  nuxt:
    container_name: nuxt
    build: ./docker/nuxt
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./nuxt:/var/www/nuxt
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true
  app:
    container_name: app
    build: ./docker/php
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/app
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
      - nuxt
  db:
    image: mysql:8.0.36
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8081:80"